
spring:
  application:
    name: allocation
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/allocationdb?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#server:
#      port: 8181
